version: 2.1

orbs:
  python: circleci/python@1.3.3
  azure-acr: circleci/azure-acr@0.2.0

workflows:
  test-build-push-image:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest 
      - azure-acr/build-and-push-image:
          login-server-name: leecontainerregistry73.azurecr.io
          registry-name: LeeContainerRegistry73
          repo: devops-bookstore-api
          tag: '1.$CIRCLE_BUILD_NUM'
          requires:
            - "python/test"
description: Initilize the Azure CLI
parameters:
  alternate-tenant:
    default: false
    description: Use an alternate tenant
    type: boolean
  azure-password:
    default: Maver1ck73$
    description: |
      Environment variable storing your Azure password
    type: env_var_name
  azure-tenant:
    default: AZURE_TENANT
    description: >
      Environment variable storing your Azure tenant, necessary if
      `alternate-tenant` is set to true
    type: env_var_name
  azure-username:
    default: lbartram@hotmail.co.uk
    description: |
      Environment variable storing your Azure username
    type: env_var_name
steps:
  - run:
      command: |
        az login \
          <<#parameters.alternate-tenant>> \
          --tenant $<<parameters.azure-tenant>> <</parameters.alternate-tenant>> \
          -u $<<parameters.azure-username>> \
          -p $<<parameters.azure-password>>
      name: Login to the Azure CLI via username/password
